"""Streamlit UI for human-in-the-loop pseudo-label verification."""


import streamlit as st
from egoindustrial.weak_supervision.ui.components import (
    label_editor,
    stats_panel,
    video_player,
)
from egoindustrial.weak_supervision.ui.export import export_verified_labels
from egoindustrial.weak_supervision.ui.state import SessionState


def main():
    st.set_page_config(
        page_title="EgoIndustrial - Pseudo-label Verification",
        page_icon="🎬",
        layout="wide",
    )

    # Initialize session state
    state = SessionState.get()

    st.title("🎬 EgoIndustrial: Pseudo-label Verification")
    st.markdown("Review and verify auto-generated pseudo-labels for training data augmentation.")

    # Sidebar
    with st.sidebar:
        st.header("📁 Data Loading")

        uploaded_file = st.file_uploader(
            "Upload pseudo-labels CSV",
            type=["csv"],
            help="CSV file generated by pseudo-labeler"
        )

        if uploaded_file:
            if st.button("Load Labels"):
                state.load_labels(uploaded_file)
                st.success(f"Loaded {len(state.labels_df)} pseudo-labels")

        if state.labels_df is not None:
            st.divider()
            st.header("🔍 Filters")

            # Confidence filter
            min_conf = st.slider(
                "Minimum Confidence",
                0.0, 1.0, 0.9, 0.05
            )

            # Class filter
            verbs = ["All"] + sorted(state.labels_df["verb_class"].unique().tolist())
            selected_verb = st.selectbox("Verb Class", verbs)

            nouns = ["All"] + sorted(state.labels_df["noun_class"].unique().tolist())
            selected_noun = st.selectbox("Noun Class", nouns)

            # Apply filters
            filtered = state.apply_filters(min_conf, selected_verb, selected_noun)
            st.info(f"Showing {len(filtered)} / {len(state.labels_df)} labels")

    # Main content
    if state.labels_df is None:
        st.info("👈 Upload a pseudo-labels CSV file to start verification")
        return

    # Stats panel
    stats_panel(state)

    # Video list
    st.header("📹 Videos to Review")

    filtered_df = state.get_filtered()

    for idx, row in filtered_df.iterrows():
        with st.expander(
            f"{row['video_path']} | "
            f"{row['verb_class']} + {row['noun_class']} | "
            f"Conf: {row['verb_confidence']:.2f}/{row['noun_confidence']:.2f} | "
            f"Frames: {row['start_frame']}-{row['end_frame']}"
        ):
            col1, col2 = st.columns([2, 1])

            with col1:
                # Video player
                video_player(row)

            with col2:
                # Label editor
                label_editor(state, idx, row)

    # Export
    st.divider()
    if st.button("💾 Export Verified Labels", type="primary"):
        output_path = export_verified_labels(state)
        st.success(f"Exported to {output_path}")

        # Download button
        with open(output_path, "rb") as f:
            st.download_button(
                "⬇️ Download CSV",
                f,
                file_name="verified_pseudo_labels.csv",
                mime="text/csv",
            )


if __name__ == "__main__":
    main()
